[theme]
primaryColor = "#c99fb5"
backgroundColor = "#0f131a"
secondaryBackgroundColor = "#171d27"
textColor = "#f3f6fb"
font = "sans serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
